name: Artifact between jobs

on: 
  workflow_dispatch:

jobs:

  generate:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: generate file
        run: |
          echo "Hello job 1">message.txt
          echo "This file is generated">messa
