name: Docker image build and push

on: 
  push: 
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checks out the code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t github-actions-practice:latest .

      - name: Docker hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Tag and push image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)

          docker tag github-actions-practice:latest \
            ${{ secrets.DOCKER_USERNAME }}/github-actions-practice:latest

          docker tag github-actions-practice:latest \
            ${{ secrets.DOCKER_USERNAME }}/github-actions-practice:sha-$SHORT_SHA

          docker push ${{ secrets.DOCKER_USERNAME }}/github-actions-practice:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/github-actions-practice:sha-$SHORT_SHA
          
